name: LiteFP
version: '${project.version}'
main: fr.lightnew.npc.LiteFP
database: true
website: https://github.com/lightnew10
api-version: '1.20'
authors: [lightnew]
softdepend: [HolographicDisplays]
commands:
  npc:
    permission: npc.litefp
  #record:
  #  permission: record.litefp
